name: Build jattach

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout another repository
        uses: actions/checkout@v4
        with:
          repository: https://github.com/jattach/jattach.git

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
