name: Build jattach

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build jattach
        run: |
          git clone https://github.com/jattach/jattach.git
          tree
          cd jattach
          make
          tree
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jattach
          path: jattach/build/jattach